-- Synthetic demonstration records. All contacts use example.test.
-- Import into an EMPTY schema after 01-03. Dates reflect the setup date.
INSERT INTO department (department_code,department_name) VALUES ('CSE','Computer Science and Engineering');
INSERT INTO department (department_code,department_name) VALUES ('ECE','Electronics and Communication');
INSERT INTO programme (department_id,programme_code,programme_name,duration_terms) VALUES (1,'BTECH-CSE','BTech Computer Science',8);
INSERT INTO programme (department_id,programme_code,programme_name,duration_terms) VALUES (2,'BTECH-ECE','BTech Electronics',8);
INSERT INTO course (department_id,course_code,course_title,credits) VALUES (1,'CS301','Database Management Systems',4);
INSERT INTO course (department_id,course_code,course_title,credits) VALUES (1,'CS302','Operating Systems',4);
INSERT INTO course (department_id,course_code,course_title,credits) VALUES (1,'CS303','Data Structures',4);
INSERT INTO course (department_id,course_code,course_title,credits) VALUES (2,'EC301','Digital Electronics',3);
INSERT INTO faculty (department_id,employee_no,full_name,email,phone) VALUES (1,'FAC001','Dr Meera Rao','meera@example.test','9000000101');
INSERT INTO faculty (department_id,employee_no,full_name,email,phone) VALUES (1,'FAC002','Arjun Nair','arjun@example.test','9000000102');
INSERT INTO faculty (department_id,employee_no,full_name,email,phone) VALUES (2,'FAC003','Dr Kavya Iyer','kavya@example.test','9000000103');
INSERT INTO semester (academic_year,term_name,start_date,end_date) VALUES ('2026-27','Odd','2026-07-12','2026-12-19');
INSERT INTO student (programme_id,registration_no,full_name,date_of_birth,email,phone,admission_date,student_status) VALUES (1,'2026CS001','Aarav Sharma','2006-01-10','student1@example.test','9000010001','2025-09-15','ACTIVE');
INSERT INTO student (programme_id,registration_no,full_name,date_of_birth,email,phone,admission_date,student_status) VALUES (1,'2026CS002','Diya Patel','2006-02-10','student2@example.test','9000010002','2025-09-15','ACTIVE');
INSERT INTO student (programme_id,registration_no,full_name,date_of_birth,email,phone,admission_date,student_status) VALUES (1,'2026CS003','Ishaan Verma','2006-03-10','student3@example.test','9000010003','2025-09-15','ACTIVE');
INSERT INTO student (programme_id,registration_no,full_name,date_of_birth,email,phone,admission_date,student_status) VALUES (1,'2026CS004','Ananya Singh','2006-04-10','student4@example.test','9000010004','2025-09-15','ACTIVE');
INSERT INTO student (programme_id,registration_no,full_name,date_of_birth,email,phone,admission_date,student_status) VALUES (1,'2026CS005','Rohan Gupta','2006-05-10','student5@example.test','9000010005','2025-09-15','ACTIVE');
INSERT INTO student (programme_id,registration_no,full_name,date_of_birth,email,phone,admission_date,student_status) VALUES (1,'2026CS006','Kavya Reddy','2006-06-10','student6@example.test','9000010006','2025-09-15','ACTIVE');
INSERT INTO student (programme_id,registration_no,full_name,date_of_birth,email,phone,admission_date,student_status) VALUES (1,'2026CS007','Aditya Rao','2006-07-10','student7@example.test','9000010007','2025-09-15','ACTIVE');
INSERT INTO student (programme_id,registration_no,full_name,date_of_birth,email,phone,admission_date,student_status) VALUES (1,'2026CS008','Meera Joshi','2006-08-10','student8@example.test','9000010008','2025-09-15','ACTIVE');
INSERT INTO student (programme_id,registration_no,full_name,date_of_birth,email,phone,admission_date,student_status) VALUES (1,'2026CS009','Vihaan Shah','2006-09-10','student9@example.test','9000010009','2025-09-15','ACTIVE');
INSERT INTO student (programme_id,registration_no,full_name,date_of_birth,email,phone,admission_date,student_status) VALUES (2,'2026EC010','Sara Khan','2006-10-10','student10@example.test','9000010010','2025-09-15','ACTIVE');
INSERT INTO student (programme_id,registration_no,full_name,date_of_birth,email,phone,admission_date,student_status) VALUES (2,'2026EC011','Arjun Das','2006-11-10','student11@example.test','9000010011','2025-09-15','ACTIVE');
INSERT INTO student (programme_id,registration_no,full_name,date_of_birth,email,phone,admission_date,student_status) VALUES (2,'2026EC012','Tara Nair','2006-12-10','student12@example.test','9000010012','2025-09-15','ACTIVE');
INSERT INTO guardian (full_name,phone,email) VALUES ('Guardian 1','9000020001','guardian1@example.test');
INSERT INTO guardian (full_name,phone,email) VALUES ('Guardian 2','9000020002','guardian2@example.test');
INSERT INTO guardian (full_name,phone,email) VALUES ('Guardian 3','9000020003','guardian3@example.test');
INSERT INTO guardian (full_name,phone,email) VALUES ('Guardian 4','9000020004','guardian4@example.test');
INSERT INTO guardian (full_name,phone,email) VALUES ('Guardian 5','9000020005','guardian5@example.test');
INSERT INTO guardian (full_name,phone,email) VALUES ('Guardian 6','9000020006','guardian6@example.test');
INSERT INTO guardian (full_name,phone,email) VALUES ('Guardian 7','9000020007','guardian7@example.test');
INSERT INTO guardian (full_name,phone,email) VALUES ('Guardian 8','9000020008','guardian8@example.test');
INSERT INTO guardian (full_name,phone,email) VALUES ('Guardian 9','9000020009','guardian9@example.test');
INSERT INTO guardian (full_name,phone,email) VALUES ('Guardian 10','9000020010','guardian10@example.test');
INSERT INTO guardian (full_name,phone,email) VALUES ('Guardian 11','9000020011','guardian11@example.test');
INSERT INTO student_guardian (student_id,guardian_id,relationship_type) VALUES (1,1,'Parent');
INSERT INTO student_guardian (student_id,guardian_id,relationship_type) VALUES (2,2,'Parent');
INSERT INTO student_guardian (student_id,guardian_id,relationship_type) VALUES (3,3,'Parent');
INSERT INTO student_guardian (student_id,guardian_id,relationship_type) VALUES (4,4,'Parent');
INSERT INTO student_guardian (student_id,guardian_id,relationship_type) VALUES (5,5,'Parent');
INSERT INTO student_guardian (student_id,guardian_id,relationship_type) VALUES (6,6,'Parent');
INSERT INTO student_guardian (student_id,guardian_id,relationship_type) VALUES (7,7,'Parent');
INSERT INTO student_guardian (student_id,guardian_id,relationship_type) VALUES (8,8,'Parent');
INSERT INTO student_guardian (student_id,guardian_id,relationship_type) VALUES (9,9,'Parent');
INSERT INTO student_guardian (student_id,guardian_id,relationship_type) VALUES (10,10,'Parent');
INSERT INTO student_guardian (student_id,guardian_id,relationship_type) VALUES (11,11,'Parent');
INSERT INTO student_guardian (student_id,guardian_id,relationship_type) VALUES (12,11,'Parent');
INSERT INTO programme_course (programme_id,course_id,recommended_term,course_type) VALUES (1,1,3,'CORE');
INSERT INTO programme_course (programme_id,course_id,recommended_term,course_type) VALUES (1,2,3,'CORE');
INSERT INTO programme_course (programme_id,course_id,recommended_term,course_type) VALUES (1,3,3,'CORE');
INSERT INTO programme_course (programme_id,course_id,recommended_term,course_type) VALUES (2,4,3,'CORE');
INSERT INTO programme_course (programme_id,course_id,recommended_term,course_type) VALUES (2,1,3,'ELECTIVE');
INSERT INTO course_offering (course_id,semester_id,faculty_id,section_code,capacity) VALUES (1,1,1,'A',12);
INSERT INTO course_offering (course_id,semester_id,faculty_id,section_code,capacity) VALUES (1,1,1,'B',2);
INSERT INTO course_offering (course_id,semester_id,faculty_id,section_code,capacity) VALUES (2,1,2,'A',12);
INSERT INTO course_offering (course_id,semester_id,faculty_id,section_code,capacity) VALUES (3,1,2,'A',12);
INSERT INTO course_offering (course_id,semester_id,faculty_id,section_code,capacity) VALUES (4,1,3,'A',6);
INSERT INTO registration (student_id,offering_id,registered_on) VALUES (1,1,'2026-07-12');
INSERT INTO registration (student_id,offering_id,registered_on) VALUES (2,1,'2026-07-12');
INSERT INTO registration (student_id,offering_id,registered_on) VALUES (3,1,'2026-07-12');
INSERT INTO registration (student_id,offering_id,registered_on) VALUES (4,1,'2026-07-12');
INSERT INTO registration (student_id,offering_id,registered_on) VALUES (5,1,'2026-07-12');
INSERT INTO registration (student_id,offering_id,registered_on) VALUES (6,1,'2026-07-12');
INSERT INTO registration (student_id,offering_id,registered_on) VALUES (7,1,'2026-07-12');
INSERT INTO registration (student_id,offering_id,registered_on) VALUES (8,1,'2026-07-12');
INSERT INTO registration (student_id,offering_id,registered_on) VALUES (9,1,'2026-07-12');
INSERT INTO registration (student_id,offering_id,registered_on) VALUES (1,3,'2026-07-12');
INSERT INTO registration (student_id,offering_id,registered_on) VALUES (2,3,'2026-07-12');
INSERT INTO registration (student_id,offering_id,registered_on) VALUES (3,3,'2026-07-12');
INSERT INTO registration (student_id,offering_id,registered_on) VALUES (4,3,'2026-07-12');
INSERT INTO registration (student_id,offering_id,registered_on) VALUES (5,3,'2026-07-12');
INSERT INTO registration (student_id,offering_id,registered_on) VALUES (6,3,'2026-07-12');
INSERT INTO registration (student_id,offering_id,registered_on) VALUES (7,3,'2026-07-12');
INSERT INTO registration (student_id,offering_id,registered_on) VALUES (8,3,'2026-07-12');
INSERT INTO registration (student_id,offering_id,registered_on) VALUES (9,3,'2026-07-12');
INSERT INTO registration (student_id,offering_id,registered_on) VALUES (10,5,'2026-07-12');
INSERT INTO registration (student_id,offering_id,registered_on) VALUES (11,5,'2026-07-12');
INSERT INTO registration (student_id,offering_id,registered_on) VALUES (12,5,'2026-07-12');
INSERT INTO class_session (offering_id,session_date,session_no,topic) VALUES (1,'2026-07-19',1,'Introduction');
INSERT INTO class_session (offering_id,session_date,session_no,topic) VALUES (1,'2026-07-26',1,'Core concepts');
INSERT INTO class_session (offering_id,session_date,session_no,topic) VALUES (1,'2026-08-02',1,'Worked examples');
INSERT INTO class_session (offering_id,session_date,session_no,topic) VALUES (1,'2026-08-09',1,'Practice session');
INSERT INTO class_session (offering_id,session_date,session_no,topic) VALUES (3,'2026-07-19',1,'Introduction');
INSERT INTO class_session (offering_id,session_date,session_no,topic) VALUES (3,'2026-07-26',1,'Core concepts');
INSERT INTO class_session (offering_id,session_date,session_no,topic) VALUES (3,'2026-08-02',1,'Worked examples');
INSERT INTO class_session (offering_id,session_date,session_no,topic) VALUES (3,'2026-08-09',1,'Practice session');
INSERT INTO class_session (offering_id,session_date,session_no,topic) VALUES (5,'2026-07-19',1,'Introduction');
INSERT INTO class_session (offering_id,session_date,session_no,topic) VALUES (5,'2026-07-26',1,'Core concepts');
INSERT INTO class_session (offering_id,session_date,session_no,topic) VALUES (5,'2026-08-02',1,'Worked examples');
INSERT INTO class_session (offering_id,session_date,session_no,topic) VALUES (5,'2026-08-09',1,'Practice session');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (1,1,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (1,2,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (1,3,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (1,4,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (2,1,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (2,2,'ABSENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (2,3,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (2,4,'ABSENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (3,1,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (3,2,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (3,3,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (3,4,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (4,1,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (4,2,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (4,3,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (4,4,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (5,1,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (5,2,'ABSENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (5,3,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (5,4,'ABSENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (6,1,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (6,2,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (6,3,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (6,4,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (7,1,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (7,2,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (7,3,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (7,4,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (8,1,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (8,2,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (8,3,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (8,4,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (9,1,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (9,2,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (9,3,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (10,5,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (10,6,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (10,7,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (10,8,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (11,5,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (11,6,'ABSENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (11,7,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (11,8,'ABSENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (12,5,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (12,6,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (12,7,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (12,8,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (13,5,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (13,6,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (13,7,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (13,8,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (14,5,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (14,6,'ABSENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (14,7,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (14,8,'ABSENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (15,5,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (15,6,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (15,7,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (15,8,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (16,5,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (16,6,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (16,7,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (16,8,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (17,5,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (17,6,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (17,7,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (17,8,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (18,5,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (18,6,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (18,7,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (18,8,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (19,9,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (19,10,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (19,11,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (19,12,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (20,9,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (20,10,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (20,11,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (20,12,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (21,9,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (21,10,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (21,11,'PRESENT');
INSERT INTO attendance (registration_id,session_id,attendance_status) VALUES (21,12,'PRESENT');
INSERT INTO examination (offering_id,exam_name,exam_date,max_marks,weight_percent) VALUES (1,'Internal','2026-08-16',50,40);
INSERT INTO examination (offering_id,exam_name,exam_date,max_marks,weight_percent) VALUES (1,'Final','2026-08-30',100,60);
INSERT INTO examination (offering_id,exam_name,exam_date,max_marks,weight_percent) VALUES (3,'Internal','2026-08-16',50,40);
INSERT INTO examination (offering_id,exam_name,exam_date,max_marks,weight_percent) VALUES (3,'Final','2026-08-30',100,60);
INSERT INTO examination (offering_id,exam_name,exam_date,max_marks,weight_percent) VALUES (5,'Internal','2026-08-16',50,40);
INSERT INTO examination (offering_id,exam_name,exam_date,max_marks,weight_percent) VALUES (5,'Final','2026-08-30',100,60);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (1,1,'SCORED',29.5e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (1,2,'SCORED',59.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (2,1,'SCORED',34.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (2,2,'SCORED',68.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (3,1,'SCORED',38.5e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (3,2,'SCORED',77.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (4,1,'SCORED',43.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (4,2,'SCORED',86.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (5,1,'SCORED',25.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (5,2,'ABSENT',NULL);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (6,1,'SCORED',29.5e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (6,2,'SCORED',59.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (7,1,'SCORED',34.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (7,2,'SCORED',68.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (8,1,'SCORED',38.5e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (8,2,'SCORED',77.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (9,1,'SCORED',43.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (10,3,'SCORED',29.5e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (10,4,'SCORED',59.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (11,3,'SCORED',34.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (11,4,'SCORED',68.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (12,3,'SCORED',38.5e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (12,4,'SCORED',77.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (13,3,'SCORED',43.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (13,4,'SCORED',86.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (14,3,'SCORED',25.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (14,4,'SCORED',50.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (15,3,'SCORED',29.5e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (15,4,'SCORED',59.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (16,3,'SCORED',34.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (16,4,'SCORED',68.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (17,3,'SCORED',38.5e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (17,4,'SCORED',77.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (18,3,'SCORED',43.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (18,4,'SCORED',86.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (19,5,'SCORED',25.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (19,6,'SCORED',50.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (20,5,'SCORED',29.5e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (20,6,'SCORED',59.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (21,5,'SCORED',34.0e0);
INSERT INTO exam_result (registration_id,exam_id,result_status,marks_obtained) VALUES (21,6,'SCORED',68.0e0);
INSERT INTO grade_scale (letter_grade,minimum_score,grade_points) VALUES ('O',90,10);
INSERT INTO grade_scale (letter_grade,minimum_score,grade_points) VALUES ('A+',80,9);
INSERT INTO grade_scale (letter_grade,minimum_score,grade_points) VALUES ('A',70,8);
INSERT INTO grade_scale (letter_grade,minimum_score,grade_points) VALUES ('B+',60,7);
INSERT INTO grade_scale (letter_grade,minimum_score,grade_points) VALUES ('B',50,6);
INSERT INTO grade_scale (letter_grade,minimum_score,grade_points) VALUES ('C',40,5);
INSERT INTO grade_scale (letter_grade,minimum_score,grade_points) VALUES ('F',0,0);
INSERT INTO fee_bill (student_id,semester_id,bill_no,description,issued_on,due_date,total_amount) VALUES (1,1,'BILL-001','Semester tuition','2026-07-12','2026-08-26',20000);
INSERT INTO fee_bill (student_id,semester_id,bill_no,description,issued_on,due_date,total_amount) VALUES (2,1,'BILL-002','Semester tuition','2026-07-12','2026-08-26',20000);
INSERT INTO fee_bill (student_id,semester_id,bill_no,description,issued_on,due_date,total_amount) VALUES (3,1,'BILL-003','Semester tuition','2026-07-12','2026-08-26',20000);
INSERT INTO fee_bill (student_id,semester_id,bill_no,description,issued_on,due_date,total_amount) VALUES (4,1,'BILL-004','Semester tuition','2026-07-12','2026-08-26',20000);
INSERT INTO fee_bill (student_id,semester_id,bill_no,description,issued_on,due_date,total_amount) VALUES (5,1,'BILL-005','Semester tuition','2026-07-12','2026-08-26',20000);
INSERT INTO fee_bill (student_id,semester_id,bill_no,description,issued_on,due_date,total_amount) VALUES (6,1,'BILL-006','Semester tuition','2026-07-12','2026-08-26',20000);
INSERT INTO fee_bill (student_id,semester_id,bill_no,description,issued_on,due_date,total_amount) VALUES (7,1,'BILL-007','Semester tuition','2026-07-12','2026-08-26',20000);
INSERT INTO fee_bill (student_id,semester_id,bill_no,description,issued_on,due_date,total_amount) VALUES (8,1,'BILL-008','Semester tuition','2026-07-12','2026-08-26',20000);
INSERT INTO fee_bill (student_id,semester_id,bill_no,description,issued_on,due_date,total_amount) VALUES (9,1,'BILL-009','Semester tuition','2026-07-12','2026-08-26',20000);
INSERT INTO fee_bill (student_id,semester_id,bill_no,description,issued_on,due_date,total_amount) VALUES (10,1,'BILL-010','Semester tuition','2026-07-12','2026-08-26',18000);
INSERT INTO fee_bill (student_id,semester_id,bill_no,description,issued_on,due_date,total_amount) VALUES (11,1,'BILL-011','Semester tuition','2026-07-12','2026-08-26',18000);
INSERT INTO fee_bill (student_id,semester_id,bill_no,description,issued_on,due_date,total_amount) VALUES (12,1,'BILL-012','Semester tuition','2026-07-12','2026-08-26',18000);
INSERT INTO payment (bill_id,receipt_no,paid_on,amount,payment_mode,transaction_reference) VALUES (1,'RCPT-001','2026-07-22',20000,'BANK_TRANSFER','DEMO-TXN-001');
INSERT INTO payment (bill_id,receipt_no,paid_on,amount,payment_mode,transaction_reference) VALUES (2,'RCPT-002','2026-07-22',8000,'BANK_TRANSFER','DEMO-TXN-002');
INSERT INTO payment (bill_id,receipt_no,paid_on,amount,payment_mode,transaction_reference) VALUES (3,'RCPT-003','2026-07-22',20000,'BANK_TRANSFER','DEMO-TXN-003');
INSERT INTO payment (bill_id,receipt_no,paid_on,amount,payment_mode,transaction_reference) VALUES (4,'RCPT-004','2026-07-22',8000,'BANK_TRANSFER','DEMO-TXN-004');
INSERT INTO payment (bill_id,receipt_no,paid_on,amount,payment_mode,transaction_reference) VALUES (5,'RCPT-005','2026-07-22',8000,'BANK_TRANSFER','DEMO-TXN-005');
INSERT INTO payment (bill_id,receipt_no,paid_on,amount,payment_mode,transaction_reference) VALUES (6,'RCPT-006','2026-07-22',8000,'BANK_TRANSFER','DEMO-TXN-006');
INSERT INTO payment (bill_id,receipt_no,paid_on,amount,payment_mode,transaction_reference) VALUES (7,'RCPT-007','2026-07-22',20000,'BANK_TRANSFER','DEMO-TXN-007');
INSERT INTO payment (bill_id,receipt_no,paid_on,amount,payment_mode,transaction_reference) VALUES (8,'RCPT-008','2026-07-22',8000,'BANK_TRANSFER','DEMO-TXN-008');
INSERT INTO payment (bill_id,receipt_no,paid_on,amount,payment_mode,transaction_reference) VALUES (9,'RCPT-009','2026-07-22',8000,'BANK_TRANSFER','DEMO-TXN-009');
INSERT INTO app_user (username,password_hash,role,student_id,faculty_id,department_id) VALUES ('admin','scrypt:32768:8:1$N3QkVmuhM8dRGCL3$b17a3b269e35384da4e7cced2822bf6ab95da62c44b4d653169f75da9f12b071f1769ae681aa92c2bc02882b987ddeb0a6a12660dda8d1119b44a4df0b8ea019','ADMIN',NULL,NULL,NULL);
INSERT INTO app_user (username,password_hash,role,student_id,faculty_id,department_id) VALUES ('faculty','scrypt:32768:8:1$I4zcJKqHAgB41tyo$0935465f0e288bc39b1d9acc95d8362164d3f11a551d5debcf078a85b38c358de1559d4970866271572fc9b388170912c464b5e45c15e9d4d6c9f8bc6176a21e','FACULTY',NULL,1,NULL);
INSERT INTO app_user (username,password_hash,role,student_id,faculty_id,department_id) VALUES ('exams','scrypt:32768:8:1$ljaHU08OvD76HE88$f4d49ea7ee530309b36c9bdc78ef421f818201c7a1b04099e04f84724a234d47b8068fe0c7d4f91c04a3d713387d573c9d8c3453c242e3d67601d72ecfdac9e0','EXAMS',NULL,NULL,NULL);
INSERT INTO app_user (username,password_hash,role,student_id,faculty_id,department_id) VALUES ('accounts','scrypt:32768:8:1$KquyCTLxxGiuXcSt$bf5e03b1fe4bf868ae3bf32fc35c1af1a7b041ea26a276bf18ef8f7d17e5187628066fff4781458257c84d86464dc4c18650f1de62cb13124d711c53b6f39487','ACCOUNTS',NULL,NULL,NULL);
INSERT INTO app_user (username,password_hash,role,student_id,faculty_id,department_id) VALUES ('student','scrypt:32768:8:1$JMsBvBOkWdIMgEEe$4755ad3bf2bf1b972f61aa24633ee5d10c914e903b9180aff2a050ad4fe666b27be6fc7d64038b8cee75f566693da0dcd78aa478df662c3da2665b71d55ae1da','STUDENT',1,NULL,NULL);
INSERT INTO app_user (username,password_hash,role,student_id,faculty_id,department_id) VALUES ('student2','scrypt:32768:8:1$DXauOBnrOgt7q59D$6e9900ef06ba25bf2ca8c7de780462194757e8b2ad60d70ffae1dd4caa897fcf9ccba8441f59cb98339a85accdfb7e4901bf974be831654b13ce64820ca43b63','STUDENT',2,NULL,NULL);
INSERT INTO app_user (username,password_hash,role,student_id,faculty_id,department_id) VALUES ('hod','scrypt:32768:8:1$5PSrh214TRXJMF3B$df0a6d9e39982a16b8b142388a14258a48f7c4c8fdd85ac79edc3258cf234c6787632c51714011166adfc506683fa8d207e510587884ebf9b73bf8b8bd16793f','HOD',NULL,NULL,1);
